//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AleksaCakicSI2317_Seminarski.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class igraci
    {
        public int igrac_id { get; set; }
        public string igrac_ime { get; set; }
        public string igrac_prezime { get; set; }
        public string igrac_broj { get; set; }
        public string igrac_tim { get; set; }
        public Nullable<int> igrac_godiste { get; set; }
    }
}
