//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AleksaCakicSI2317_Seminarski.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timovi
    {
        public int tim_id { get; set; }
        public string tim_ime { get; set; }
        public Nullable<int> tim_osnovan { get; set; }
        public string tim_trener { get; set; }
    }
}
