# Use postgres/example model.user/password credentials
# Author: Aleksa Cakic
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
