create sequence hibernate_sequence;

alter sequence hibernate_sequence owner to postgres;



create table "igrac"
(
    igrac_id      integer generated by default as identity (cycle)
        constraint "Igrac_pkey"
            primary key,
    igrac_ime     varchar(50),
    igrac_prezime varchar(50),
    igrac_broj    integer,
    igrac_tim     varchar(50),
    igrac_godiste integer
);

comment on table "Igrac" is 'Tabela igraca';

alter table "Igrac"
    owner to postgres;

create table tim
(
    tim_id      integer not null
        constraint tim_pkey
            primary key,
    tim_ime     varchar(50),
    tim_osnovan integer,
    tim_trener  varchar(50)
);

alter table tim
    owner to postgres;

create table igrac
(
    igrac_id      integer not null
        constraint igrac_pkey
            primary key,
    igrac_broj    integer,
    igrac_godiste integer,
    igrac_ime     varchar(255),
    igrac_prezime varchar(255),
    igrac_tim     varchar(255)
);

alter table igrac
    owner to postgres;

